# Default values for doh-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: satishweb/doh-server
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

env:
  DEBUG: "0"
  UPSTREAM_DNS_SERVER: "udp:8.8.8.8:53"
  DOH_HTTP_PREFIX: "/dns-query"
  DOH_SERVER_LISTEN: ":80"
  DOH_SERVER_TIMEOUT: "10"
  DOH_SERVER_TRIES: "3"
  DOH_SERVER_VERBOSE: "false"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  domainName: "doh.your-domain.com"
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

probesQuery: name=google.com

nodeSelector: {}

tolerations: []

affinity: {}
